In [1]:
import os
import math
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from numpy.linalg import eig

from util.ZigZag0 import ZigZag
from util.CalcReturns import CalcReturns

from matplotlib.animation import FuncAnimation

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [2]:
#eth = np.array(pd.read_csv('fxclub_ETHUSD1.csv', header=0).Close)
#btc = np.array(pd.read_csv('fxclub_BTCUSD1.csv', header=0).Close)
#dsh = np.array(pd.read_csv('fxclub_DSHUSD1.csv', header=0).Close)

#eth = np.array(pd.read_csv('fxopen_ETHUSD1.csv', header=0).Close)
#btc = np.array(pd.read_csv('fxopen_BTCUSD1.csv', header=0).Close)
#mbt = np.array(pd.read_csv('fxopen_MBTUSD1.csv', header=0).Close)
#eur = np.array(pd.read_csv('fxopen_EURUSD1.csv', header=0).Close)
#gbp = np.array(pd.read_csv('fxopen_GBPUSD1.csv', header=0).Close)
#rub = np.array(pd.read_csv('fxopen_USDRUB1.csv', header=0).Close)

btc = np.array(pd.read_csv('gdax_BTCUSD1.csv', header=0).Close)
eth = np.array(pd.read_csv('gdax_ETHUSD1.csv', header=0).Close)
bch = np.array(pd.read_csv('gdax_BCHUSD1.csv', header=0).Close)
ltc = np.array(pd.read_csv('gdax_LTCUSD1.csv', header=0).Close)

coin = np.row_stack((btc, eth, bch, ltc))
text = ['btc', 'eth', 'bch', 'ltc']

In [3]:
def SSA(X):    
    cov_matrix = np.dot(X.T, X)
    w, v = eig(cov_matrix)
    
    S = []
    for i in range(len(v)):
        t = np.matmul(X, v[i].T)
        S.append(t)

    return v, S

def plot_SSA(X, S, t):
    n = len(S)
    for i in range(n):
        for j in range(i):
            if i != j:
                fig = plt.figure()
                
                ax = plt.subplot(3,1,1)
                ax.plot(X[i], label = t[i])
                ax.legend()
                
                ax = plt.subplot(3,1,2)
                ax.plot(X[j], label = t[j])
                ax.legend()
                
                ax = plt.subplot(3,1,3)
                ax.scatter(X[i], X[j])                
                ax.legend()
                
                plt.show()
    
    fig = plt.figure()
    for i in range(n):    
        ax = plt.subplot(n,1,i+1)
        ax.plot(S[i], label = 'S[' + str(i) + ']')
        ax.legend()
        
    plt.show()

In [4]:
%matplotlib

X = coin.T

L = len(X)
i = 0



v, S = SSA(X[i:i+L])
print v

plot_SSA(X[i:i+L].T, S, text)


Using matplotlib backend: TkAgg
[[ 0.98951827 -0.14129166  0.02981879 -0.00105081]
 [ 0.07981525  0.37420032 -0.88489218 -0.26564916]
 [ 0.11873587  0.91333376  0.38850184  0.02809903]
 [ 0.01961926  0.07636902 -0.25523126  0.96365962]]


In [8]:
%matplotlib

plt.plot(S[3])

#v1 = np.array([0.08, -0.7, -0.7])
#s1 = np.matmul(X, v1.T)

#plt.figure()
#ax = plt.subplot(1,1,1)
#ax.plot(S[1], label = 'S[1]')
#ax.plot(s1, label = 's1')
#ax.legend()


Using matplotlib backend: TkAgg


In [12]:
p = [11074.0, 858.120, 619.600]
s = v[1]

e = np.dot(p,s)

v[1]



# 'btc'  'eth'    'dsh'    'iot'  'ltc'  'xpr'
# 62.77  -705.12  -706.28  4.88   1.30    0.57

# 'btc'       'eth'        'dsh'    
# 8410        -68946       -71941


array([ 0.0841051 , -0.68946819, -0.71941639])

In [13]:
%matplotlib

#gdax   = np.array(pd.read_csv('gdax__BTCUSD1.csv', header=0).Close)
#fxopen = np.array(pd.read_csv('fxopen__BTCUSD1.csv', header=0).Close)

sub = gdax - fxopen

#plt.plot(gdax, label='gdax (BTCUSD 1 min)')
#plt.plot(fxopen, label='fxopen (BTCUSD 1 min)')
#plt.plot(sub)
#plt.legend()

#w = np.array([0.08, -0.7, 0.7])
#e = np.dot(X,w.T)

#plt.plot(e, label='e')
#plt.plot(S[1], label='S[1]')
#plt.legend()


Using matplotlib backend: TkAgg


In [5]:
#T=coin
#xT=(9200, 10200)
#yT=(800, 850)

#fig, ax0 = plt.subplots(nrows=1, ncols=1)
#ax0.set(xlim=xT, ylim=yT)

#def animate(i):
#    ax0.scatter(T[0][i], T[1][i], marker='.')
    
#anim = FuncAnimation(fig, animate, interval=1, frames=len(T[0])-1)
#plt.draw()
#plt.show()

In [ ]:
#%matplotlib

#L = 1024
#X = coin.T

#S = []
#for i in range(0, len(X.T[0]) - L):
#    v, _, _ = SSA(X[i:L+i])
#    S.append(v[1])
    
#S = np.array(S)
#S = S.T

##plt.scatter(S.T[0], S.T[1])

##T=S
##xT=(-0.15, 0.1)
##yT=(-1.5, 1.5)

##fig, ax0 = plt.subplots(nrows=1, ncols=1)
##ax0.set(xlim=xT, ylim=yT)

##def animate(i):
##    ax0.scatter(T[0][i], T[1][i], marker='.')
    
##anim = FuncAnimation(fig, animate, interval=1, frames=len(T[0])-1)
##plt.draw()
##plt.show()

#plt.figure()

#plt.subplot(2,1,1)
#plt.plot(S[0])

#plt.subplot(2,1,2)
#plt.plot(X.T[0][L+1:-1])

##plt.subplot(4,1,3)
##plt.plot(X.T[1][1025:2948])

##plt.subplot(4,1,4)
##plt.plot(S[1])
