In [1]:
import os
import math
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from numpy.linalg import eig

from util.ZigZag0 import ZigZag
from util.calc_returns import DifRet, iDifRet

from matplotlib.animation import FuncAnimation

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [2]:
#eth = np.array(pd.read_csv('fxclub_ETHUSD1.csv', header=0).Close)
#btc = np.array(pd.read_csv('fxclub_BTCUSD1.csv', header=0).Close)
#dsh = np.array(pd.read_csv('fxclub_DSHUSD1.csv', header=0).Close)

#eth = np.array(pd.read_csv('fxopen_ETHUSD1.csv', header=0).Close)
#btc = np.array(pd.read_csv('fxopen_BTCUSD1.csv', header=0).Close)
#mbt = np.array(pd.read_csv('fxopen_MBTUSD1.csv', header=0).Close)
#eur = np.array(pd.read_csv('fxopen_EURUSD1.csv', header=0).Close)
#gbp = np.array(pd.read_csv('fxopen_GBPUSD1.csv', header=0).Close)
#rub = np.array(pd.read_csv('fxopen_USDRUB1.csv', header=0).Close)

#btc = np.array(pd.read_csv('gdax_BTCUSD1.csv', header=0).Close)
#eth = np.array(pd.read_csv('gdax_ETHUSD1.csv', header=0).Close)
#bch = np.array(pd.read_csv('gdax_BCHUSD1.csv', header=0).Close)
#ltc = np.array(pd.read_csv('gdax_LTCUSD1.csv', header=0).Close)

bch = np.array(pd.read_csv('bitfinex_BCHUSD1.csv', header=0).Close)
btc = np.array(pd.read_csv('bitfinex_BTCUSD1.csv', header=0).Close)
dsh = np.array(pd.read_csv('bitfinex_DSHUSD1.csv', header=0).Close)
eos = np.array(pd.read_csv('bitfinex_EOSUSD1.csv', header=0).Close)
etc = np.array(pd.read_csv('bitfinex_ETCUSD1.csv', header=0).Close)
eth = np.array(pd.read_csv('bitfinex_ETHUSD1.csv', header=0).Close)
ltc = np.array(pd.read_csv('bitfinex_LTCUSD1.csv', header=0).Close)
neo = np.array(pd.read_csv('bitfinex_NEOUSD1.csv', header=0).Close)
xmr = np.array(pd.read_csv('bitfinex_XMRUSD1.csv', header=0).Close)
xrp = np.array(pd.read_csv('bitfinex_XRPUSD1.csv', header=0).Close)


#coin = np.row_stack((bch, btc, dsh, eos, etc, eth, ltc, neo, xmr, xrp))
#text = ['bch', 'btc', 'dsh', 'eos', 'etc', 'eth', 'ltc', 'neo', 'xmr', 'xrp']

coin = np.row_stack((btc, dsh, eth))
text = ['btc', 'dsh', 'eth']

In [3]:
def SSA(S):
    R = DifRet(S)
    cov_matrix = np.dot(R.T, R)
    w, v = eig(cov_matrix)
    
    R0 = np.matmul(v, R.T)
    S0 = np.matmul(v, X[0].T)
    
    F = iDifRet(S0, R0.T)    
    return v, F

def plot_SSA(S, F, t):
    
    R = DifRet(S.T)
    
    n = len(F[0,:])
    for i in range(n):
        for j in range(i):
            if i != j:
                fig = plt.figure()
                
                ax = plt.subplot(3,1,1)
                ax.plot(S[i], label = t[i])
                ax.legend()
                
                ax = plt.subplot(3,1,2)
                ax.plot(S[j], label = t[j])
                ax.legend()
                
                ax = plt.subplot(3,1,3)
                ax.scatter(R.T[i], R.T[j])                
                ax.legend()
                
                plt.show()
    
    fig = plt.figure()
    for i in range(n):    
        ax = plt.subplot(n,1,i+1)
        ax.plot(F.T[i], label = 'F[' + str(i) + ']')
        ax.legend()
        
    plt.show()

In [4]:
%matplotlib
X = coin.T

v, S = SSA(X)
print v

plot_SSA(X.T, S, text)


Using matplotlib backend: TkAgg
[[-0.55745494 -0.74889142 -0.35833732]
 [-0.7986991   0.60155168 -0.0146737 ]
 [-0.22654743 -0.27802377  0.93347686]]


In [16]:
%matplotlib

T = iDifRet(coin.T[0], X)

print X

plt.plot(X[:,2])

#plt.plot(S[1])

#v1 = np.array([0.08, -0.7, -0.7])
#s1 = np.matmul(X, v1.T)

#plt.figure()
#ax = plt.subplot(1,1,1)
#ax.plot(S[1], label = 'S[1]')
#ax.plot(s1, label = 's1')
#ax.legend()


Using matplotlib backend: TkAgg
[[  9352.7     577.5     826.51]
 [  9353.2     578.6     826.8 ]
 [  9334.      578.6     826.5 ]
 ..., 
 [ 10554.      553.97    790.74]
 [ 10559.      553.97    790.67]
 [ 10565.      553.9     790.67]]


In [12]:
p = [11074.0, 858.120, 619.600]
s = v[1]

e = np.dot(p,s)

v[1]



# 'btc'  'eth'    'dsh'    'iot'  'ltc'  'xpr'
# 62.77  -705.12  -706.28  4.88   1.30    0.57

# 'btc'       'eth'        'dsh'    
# 8410        -68946       -71941


array([ 0.0841051 , -0.68946819, -0.71941639])

In [21]:
%matplotlib

gdax   = np.array(pd.read_csv('gdax__BTCUSD1.csv', header=0).Close)
fxopen = np.array(pd.read_csv('fxopen__BTCUSD1.csv', header=0).Close)
fxclub = np.array(pd.read_csv('fxclub__BTCUSD1.csv', header=0).Close)
bitfinex = np.array(pd.read_csv('bitfinex__BTCUSD1.csv', header=0).Close)

plt.plot(gdax[1:10000], label='gdax (BTCUSD 1 min)')
plt.plot(fxopen[1:10000], label='fxopen (BTCUSD 1 min)')
plt.plot(fxclub[1:10000], label='fxclub (BTCUSD 1 min)')
plt.plot(bitfinex[1:10000], label='bitfinex (BTCUSD 1 min)')
plt.legend()

#w = np.array([0.08, -0.7, 0.7])
#e = np.dot(X,w.T)

#plt.plot(e, label='e')
#plt.plot(S[1], label='S[1]')
#plt.legend()


Using matplotlib backend: TkAgg


In [5]:
#T=coin
#xT=(9200, 10200)
#yT=(800, 850)

#fig, ax0 = plt.subplots(nrows=1, ncols=1)
#ax0.set(xlim=xT, ylim=yT)

#def animate(i):
#    ax0.scatter(T[0][i], T[1][i], marker='.')
    
#anim = FuncAnimation(fig, animate, interval=1, frames=len(T[0])-1)
#plt.draw()
#plt.show()

In [ ]:
#%matplotlib

#L = 1024
#X = coin.T

#S = []
#for i in range(0, len(X.T[0]) - L):
#    v, _, _ = SSA(X[i:L+i])
#    S.append(v[1])
    
#S = np.array(S)
#S = S.T

##plt.scatter(S.T[0], S.T[1])

##T=S
##xT=(-0.15, 0.1)
##yT=(-1.5, 1.5)

##fig, ax0 = plt.subplots(nrows=1, ncols=1)
##ax0.set(xlim=xT, ylim=yT)

##def animate(i):
##    ax0.scatter(T[0][i], T[1][i], marker='.')
    
##anim = FuncAnimation(fig, animate, interval=1, frames=len(T[0])-1)
##plt.draw()
##plt.show()

#plt.figure()

#plt.subplot(2,1,1)
#plt.plot(S[0])

#plt.subplot(2,1,2)
#plt.plot(X.T[0][L+1:-1])

##plt.subplot(4,1,3)
##plt.plot(X.T[1][1025:2948])

##plt.subplot(4,1,4)
##plt.plot(S[1])
